apim/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),   
    path('inventario/', include("inventario.urls", namespace="inventario")),
]

inventario/urls.py
from django.urls import path

from . import views

app_name = "inventario"

urlpatterns =[    
    path("", views.ServidorList.as_view(), name="list"),
    path("create/", views.ServidorCreate.as_view(), name="create"),
    path("update/<int:pk>/", views.ServidorUpdate.as_view(), name="update"),
    path("detail/<int:pk>/", views.ServidorDetail.as_view(), name="detail"),
    path("delete/<int:pk>/", views.ServidorDelete.as_view(), name="delete"),
    path('export/csv-database-write/', views.csv_database_write, name='csv_database_write'),
]

inventario/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Dominio(models.Model):
    nome  = models.CharField(max_length=255)
    local = models.CharField(max_length=255)
    
    def __str__(self):        
        return self.nome

class Responsavel(models.Model):
    nome  = models.CharField(max_length=255)
    
    def __str__(self):        
        return self.nome

class Ambiente(models.Model):
    nome  = models.CharField(max_length=255)
    
    def __str__(self):        
        return self.nome

class Operacional(models.Model):
    nome  = models.CharField(max_length=255)
    
    def __str__(self):        
        return self.nome

class Ferramenta(models.Model):
    nome  = models.CharField(max_length=255)
    descricao = models.CharField(max_length=255)

    def __str__(self):        
        return self.nome

class Versao(models.Model):
    nome  = models.CharField(max_length=255)
    descricao = models.CharField(max_length=255)

    def __str__(self):        
        return self.nome


class Pci(models.Model):
    nome  = models.CharField(max_length=50)

    def __str__(self):        
        return self.nome

class Externo(models.Model):
    nome  = models.CharField(max_length=50)
    
    def __str__(self):        
        return self.nome

class Vlan(models.Model):
    nome  = models.CharField(max_length=50)
    mascara  = models.CharField(max_length=50)
    gateway  = models.CharField(max_length=50)
    
    def __str__(self):        
        return self.nome        

class Contexto(models.Model):
    nome  = models.CharField(max_length=50)
    
    def __str__(self):        
        return self.nome

class Empresa(models.Model):
    nome  = models.CharField(max_length=50)
    
    def __str__(self):        
        return self.nome


class Url(models.Model):
    endereco = models.CharField(max_length=255)
    
    def __str__(self):        
        return self.endereco  


class Servidor(models.Model):
    nome = models.CharField(max_length=255)
    ambiente = models.ForeignKey(Ambiente, on_delete=models.CASCADE)
    responsavel = models.ForeignKey(Responsavel, on_delete=models.CASCADE)
    dominio = models.ForeignKey(Dominio, on_delete=models.CASCADE)
    ip = models.CharField(max_length=255)
    os = models.ForeignKey(Operacional, on_delete=models.CASCADE)
    ferramenta = models.ForeignKey(Ferramenta, on_delete=models.CASCADE)
    versao = models.ForeignKey(Versao, on_delete=models.CASCADE)
    descricao = models.CharField(max_length=255)
    pci = models.ForeignKey(Pci, on_delete=models.CASCADE)
    externo = models.ForeignKey(Externo, on_delete=models.CASCADE)
    vlan = models.ForeignKey(Vlan, on_delete=models.CASCADE)
    contexto = models.ForeignKey(Contexto, on_delete=models.CASCADE)
    disco = models.CharField(max_length=255)
    memoria = models.CharField(max_length=255)
    vcpu = models.CharField(max_length=255)
    empresa = models.ForeignKey(Empresa, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.nome   
    
    #def get_absolute_url(self):
    #    return reverse("servidor:detail", kwargs={"nome": self.nome})

    
class ServidorUrl(models.Model):
    servidor = models.ForeignKey(Servidor, on_delete=models.CASCADE)
    url = models.ForeignKey(Url, on_delete=models.CASCADE)
    
    def __str__(self):        
        return self.servidor       
          

inventario/views.py
import csv
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import ListView, CreateView, UpdateView, DetailView
from django.views.generic.edit import DeleteView
from django.shortcuts import render
from inventario.models import Servidor

def csv_database_write(request):
    
    # Get all data from UserDetail Databse Table
    servidores = Servidor.objects.all()

    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="csv_database_write.csv"'

    writer = csv.writer(response)
    writer.writerow(['Nome', 'Ambiente', 'Responsavel', 'Dominio'])

    for server in servidores:
        writer.writerow([server.nome, server.ambiente, server.responsavel, server.dominio])

    return response

class ServidorList(ListView):
    model = Servidor
    queryset = Servidor.objects.all()
    
class ServidorCreate(CreateView):
    model = Servidor
    fields = '__all__'
    success_url = reverse_lazy('inventario:list')
    
class ServidorUpdate(UpdateView):
    model = Servidor
    fields = '__all__'
    success_url = reverse_lazy('inventario:list')    
    
class ServidorDetail(DetailView):
    model = Servidor
    queryset = Servidor.objects.all()       
        
class ServidorDelete(DeleteView):
    model = Servidor
    queryset = Servidor.objects.all() 
    success_url = reverse_lazy('inventario:list')     

    

inventario/templates/inventario/base.html
{%  load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/inventario.css' %}" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="home" href="/inventario">Home</a>  
          <a class="nav-item nav-link" id="clientecreate" href="/inventario/create">Adicionar-Servidor</a>        
        </div>
      </div>
    </nav>
    <div class="container-fluid">
    {% block content %}
    {% endblock %}
    </div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>    
  </body>
</html>

inventario/templates/inventario/servidor_confirm_delete.html
{% extends "inventario/base.html" %}

{% block title %} Servidor {% endblock %}

{% block content %}
    <ul class="list-group list-group-flush" id="servidor_delete"> 
        <li class="list-group-item">
        Confirma a exclusão do Servidor '{{ object.nome }}' ?
        <form action="." method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-primary" value="Sim">
            <a href="{% url 'inventario:list' %}" class="btn btn-secondary" role="button" aria-pressed="true">Não</a>
        </form>
        </li>         
    </ul> 
{% endblock %}

inventario/templates/inventario/servidor_detail.html
{% extends "inventario/base.html" %}

{% block title %} Cliente{% endblock %}

{% block content %}
<ul class="list-group list-group-flush" id="servidor_detail"> 
        <li class="list-group-item">
            {{ object.dominio }}  
        </li>  
        <li class="list-group-item">
            {{ object.ip }}  
        </li> 
        <li class="list-group-item">
            {{ object.os }}  
        </li> 
        <li class="list-group-item">
            {{ object.disco }}  
        </li> 
        <li class="list-group-item">
            {{ object.memoria }}  
        </li> 
        <li class="list-group-item">
            {{ object.vcpu }}  
        </li>                                       
    </ul> 


    <a href="/inventario" class="btn btn-primary active" role="button">Voltar</a>   
{% endblock %}

inventario/templates/inventario/servidor_form.html
{% extends "inventario/base.html" %}

{% load bootstrap %}

{% block title %} Lista de Servidores {% endblock %}

{% block content %}
    <form action='.' method='post'>
            {% csrf_token %}
            {{ form|bootstrap }}
            <input type="submit" class="btn btn-primary" value="Salvar">
            <a href="{% url 'inventario:list' %}" class="btn btn-secondary" role="button" aria-pressed="true">Cancelar</a>
    </form>
{% endblock %}

inventario/templates/inventario/servidor_list.html
{% extends "inventario/base.html" %}

{% block title %} Lista de Servidores {% endblock %}

{% block content %}
<ul class="list-group list-group-flush" id="servidor_detail"> 
    <table class="table">
        <thead>
            <tr>
                <th>Servidor</th>
                <th>Ambiente</th>
                <th>Responsável</th>
                <th>Domínio</th>
                <th>IP</th>
                <th>SO</th>
                <th>Ferramenta</th>
                <th>Versão</th>
                <th>Descrição</th>
                <th>PCI</th>
                <th>Contexto</th>
                <th>Empresa</th>             
                <th>Ação</th>
            </tr>
        </thead>
    <tbody>
    {% for row in object_list %}  
            <tr>
                <td style="width:1px; white-space:nowrap;">{{ row.nome }}</td>
                <td style="width:1px; white-space:nowrap;">{{ row.ambiente }}</td>
                <td style="width:1px; white-space:nowrap;">{{ row.responsavel }}</td>
                <td style="width:1px; white-space:nowrap;">{{ row.dominio }}</td>
                <td style="width:1px; white-space:nowrap;">{{ row.ip }}</td>
                <td style="width:1px; white-space:nowrap;">{{ row.os }}</td>
                <td style="width:1px; white-space:nowrap;">{{ row.ferramenta }}</td>
                <td style="width:1px; white-space:nowrap;">{{ row.versao }}</td>
                <td style="width:1px; white-space:nowrap;">{{ row.descricao }}</td>
                <td style="width:1px; white-space:nowrap;">{{ row.pci }}</td>
                <td style="width:1px; white-space:nowrap;">{{ row.contexto }}</td>
                <td style="width:1px; white-space:nowrap;">{{ row.empresa }}</td>
                <td style="width:1px; white-space:nowrap;">
                    <a href="{% url 'inventario:detail' pk=row.id %}" class="btn btn-primary" role="button" aria-pressed="true">Detalhes</a>
                    <a href="{% url 'inventario:update' pk=row.id %}" class="btn btn-secondary" role="button" aria-pressed="true">Editar</a>
                    <a href="{% url 'inventario:delete' pk=row.id %}" class="btn btn-secondary" role="button" aria-pressed="true">Deletar</a>
                </td>
            </tr>
    {% endfor %}     
    </tr>
    </tbody>
    </table> 
    <a href="{% url 'inventario:csv_database_write' %}" class="btn btn-secondary">Database Data CSV Write Operation</a>
</ul>
{% endblock %}